version: '2'
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - '.env.web'
    entrypoint: /myapp/rails-entrypoint.sh
    command: rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres
    ports:
      - "13306:3306"
    env_file:
      - '.env.db'
    volumes:
      - /root/myapp_db:/var/lib/postgresql/data
